In [1]:
import numpy as np
import pandas as pd

In [20]:
credits = pd.read_csv('tmdb_5000_credits.csv')

In [21]:
movies = pd.read_csv('tmdb_5000_movies.csv')

In [22]:
credits.head(5)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [24]:
credits.isnull().sum

<bound method DataFrame.sum of       movie_id  title   cast   crew
0        False  False  False  False
1        False  False  False  False
2        False  False  False  False
3        False  False  False  False
4        False  False  False  False
...        ...    ...    ...    ...
4798     False  False  False  False
4799     False  False  False  False
4800     False  False  False  False
4801     False  False  False  False
4802     False  False  False  False

[4803 rows x 4 columns]>

In [25]:
movies.isnull().sum

<bound method DataFrame.sum of       budget  genres  homepage     id  keywords  original_language  \
0      False   False     False  False     False              False
1      False   False     False  False     False              False
2      False   False     False  False     False              False
3      False   False     False  False     False              False
4      False   False     False  False     False              False
...      ...     ...       ...    ...       ...                ...
4798   False   False      True  False     False              False
4799   False   False      True  False     False              False
4800   False   False     False  False     False              False
4801   False   False     False  False     False              False
4802   False   False      True  False     False              False

      original_title  overview  popularity  production_companies  \
0              False     False       False                 False
1              False     False       False                 False
2              False     False       False                 False
3              False     False       False                 False
4              False     False       False                 False
...              ...       ...         ...                   ...
4798           False     False       False                 False
4799           False     False       False                 False
4800           False     False       False                 False
4801           False     False       False                 False
4802           False     False       False                 False

      production_countries  release_date  revenue  runtime  spoken_languages  \
0                    False         False    False    False             False
1                    False         False    False    False             False
2                    False         False    False    False             False
3                    False         False    False    False             False
4                    False         False    False    False             False
...                    ...           ...      ...      ...               ...
4798                 False         False    False    False             False
4799                 False         False    False    False             False
4800                 False         False    False    False             False
4801                 False         False    False    False             False
4802                 False         False    False    False             False

      status  tagline  title  vote_average  vote_count
0      False    False  False         False       False
1      False    False  False         False       False
2      False    False  False         False       False
3      False    False  False         False       False
4      False    False  False         False       False
...      ...      ...    ...           ...         ...
4798   False    False  False         False       False
4799   False    False  False         False       False
4800   False     True  False         False       False
4801   False    False  False         False       False
4802   False     True  False         False       False

[4803 rows x 20 columns]>

In [26]:
credits.shape

(4803, 4)

In [27]:
movies.shape

(4803, 20)

In [28]:
movies = movies.merge(credits,on='title')

In [29]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [31]:
movies = movies[
['movie_id','title','overview','genres','keywords','cast','crew']]

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [34]:
movies.dropna(inplace=True)

In [35]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [36]:
import ast

In [40]:
def convert(text):
    
    L = []
    
    for i in ast.literal_eval(text):
        L.append(i['name'])
        
    return L

In [41]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [42]:
# Extracting Top 10

In [43]:
def convert_cast(text):

    L = []
    counter = 0

    for i in ast.literal_eval(text):

        if counter != 3:

            L.append(i['name'])
            counter += 1

        else:
            break

    return L

In [44]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [45]:
def fetch_director(text):

    L=[]

    for i in ast.literal_eval(text):

        if i['job']=="Director":

            L.append(i['name'])
            break

    return L

In [46]:
movies['crew']=movies['crew'].apply(fetch_director)

In [47]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [48]:
movies['genres'] = movies['genres'].apply(
lambda x:[i.replace(" ","") for i in x]
)

movies['keywords'] = movies['keywords'].apply(
lambda x:[i.replace(" ","") for i in x]
)

movies['cast'] = movies['cast'].apply(
lambda x:[i.replace(" ","") for i in x]
)

movies['crew'] = movies['crew'].apply(
lambda x:[i.replace(" ","") for i in x]
)

In [49]:
movies['tags'] = (
movies['overview']
+
movies['genres']
+
movies['keywords']
+
movies['cast']
+
movies['crew']
)

In [50]:
new_df = movies[['movie_id','title','tags']]

In [51]:
new_df['tags'] = new_df['tags'].apply(
lambda x:" ".join(x)
)

/var/folders/np/rgt7_0wj7w9fxy6732r521840000gn/T/ipykernel_31379/1321705512.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(

In [52]:
new_df['tags'] = new_df['tags'].apply(
lambda x:x.lower()
)

/var/folders/np/rgt7_0wj7w9fxy6732r521840000gn/T/ipykernel_31379/1402015918.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(

In [53]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [54]:
def stem(text):

    y=[]

    for i in text.split():

        y.append(ps.stem(i))

    return " ".join(y)

In [55]:
new_df['tags'] = new_df['tags'].apply(stem)

/var/folders/np/rgt7_0wj7w9fxy6732r521840000gn/T/ipykernel_31379/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
cv = CountVectorizer(
max_features=5000,
stop_words='english'
)

In [58]:
vectors = cv.fit_transform(
new_df['tags']
).toarray()

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
similarity = cosine_similarity(vectors)

In [61]:
similarity.shape

(4806, 4806)

In [62]:
def recommend(movie):

    movie_index = new_df[
        new_df['title']==movie
    ].index[0]

    distances = similarity[movie_index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )[1:6]

    for i in movie_list:

        print(
        new_df.iloc[i[0]].title,
        round(i[1]*100,2)
        )

In [63]:
recommend("Avatar")

Aliens vs Predator: Requiem 28.68
Aliens 26.9
Falcon Rising 26.05
Independence Day 25.56
Titan A.E. 25.04

In [64]:
import pickle

In [65]:
pickle.dump(
new_df,
open('movie_list.pkl','wb')
)

In [66]:
pickle.dump(
similarity,
open('similarity.pkl','wb')
)

In [68]:
API_KEY="74e3d0f1c912d145a8f53705df7ec98c"